import Navbar from "@/components/navbar/navbar";
import LoginModal from "@/components/modal/loginform";
import RegisterModal from "@/components/modal/signupform";
import { Outfit } from "next/font/google";
import ToasterProvider from "@/providers/toaster-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";
import ClientOnly from "@/components/clientOnly/clientOnly";
import getCurrentUser from "@/app/actions/getCurrentUser";

const font = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Custom Crm",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <Navbar currentUser={currentUser} />
          <RegisterModal />
          <LoginModal />
        </ClientOnly>

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
